version: '3.1'

services:
  db:
    image: mysql
    container_name: distancedb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - distance-network

  app:
    image: junseok1204/distance-0.0.16-snapshot
    container_name: app-container
    ports:
      - 6580:8080
    env_file:
      - "./.env"
    environment:
      - TZ=Asis/Seoul
    depends_on:
      - db
    links:
      - db
    networks:
      - distance-network
    restart: always

networks:
  distance-network:

volumes:
  mysql-data:
