version: '3.1'

services:
  db:
    image: mysql
    container_name: distancedb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - distance-networked

  app:
    image: junseok1204/distance-0.0.25-snapshot
    container_name: app-container
    ports:
      - 8080:8080
    env_file:
      - "./.env"
    environment:
      - TZ=Asis/Seoul
    depends_on:
      - db
    links:
      - db
    networks:
      - distance-networked
    restart: always

  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    container_name: distance-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - distance-networked

  certbot:
      image: certbot/certbot:latest
      restart: unless-stopped
      volumes:
        - ./nginx/certbot/conf:/etc/letsencrypt
        - ./nginx/certbot/www:/var/www/certbot
      networks:
        - distance-networked
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


networks:
  distance-networked:

volumes:
  mysql-data:
