spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: info
  org.springframework.security: DEBUG

jwt:
  header: ${JWT_HEADER}
  secret: ${JWT_SECRET_KEY}
  token-validity-in-seconds: ${JWT_EXPIRATION}

fcm:
  project-id: ${PROJECT_ID}
  private-key: ${PRIVATE_KEY}
  private-key-id: ${PRIVATE_KEY_ID}
  client-email: ${CLIENT_EMAIL}
  client-id: ${CLIENT_ID}