spring:
  datasource:
    url: jdbc:mysql://localhost:3306/distance?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&&allowPublicKeyRetrieval=true
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: info
  org.springframework.security: DEBUG

jwt:
  header: ${JWT_HEADER}
  secret: ${JWT_SECRET_KEY}
  token-validity-in-seconds: ${JWT_EXPIRATION}