name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: actions/checkout@v2
    - name: Set YML
      run: |
          mkdir -p src/main/resources
          find src
    - name: Add permission
      run: chmod +x gradlew

    - name: Test with Gradle
      run: ./gradlew test

    - name: Clean with Gradle
      run: ./gradlew clean

    - name: Build with Gradle
      run: ./gradlew clean build
